//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace household_management.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HoKhauEntities : DbContext
    {
        public HoKhauEntities()
            : base("name=HoKhauEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Family_Household> Family_Household { get; set; }
        public virtual DbSet<Household_Registration> Household_Registration { get; set; }
        public virtual DbSet<Population> Populations { get; set; }
        public virtual DbSet<Temporary_Absence> Temporary_Absence { get; set; }
        public virtual DbSet<Temporary_Residence> Temporary_Residence { get; set; }
        public virtual DbSet<Transfer_Household> Transfer_Household { get; set; }
        public virtual DbSet<UserRole> UserRoles { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
