//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace household_management.Model
{
    using household_management.ViewModel;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Runtime.CompilerServices;

    public partial class Population : INotifyPropertyChanged
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Population()
        {
            this.Family_Household = new HashSet<Family_Household>();
            this.Family_Household1 = new HashSet<Family_Household>();
            this.Household_Registration = new HashSet<Household_Registration>();
            this.Temporary_Absence = new HashSet<Temporary_Absence>();
            this.Temporary_Residence = new HashSet<Temporary_Residence>();
            this.Transfer_Household = new HashSet<Transfer_Household>();

        }
        public event PropertyChangedEventHandler PropertyChanged;

        protected virtual void OnPropertyChanged([CallerMemberName] string propertyName = null)
        {
            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
        }

        private int stt;
        public int Stt { get => stt; set { stt = value; OnPropertyChanged(); } }
        private string id;
        public  string Id { get => id; set { id = value; OnPropertyChanged(); } }
        private string name;
        public  string Name { get => name; set { name = value; OnPropertyChanged(); } }
        private string photo;
        public  string Photo { get => photo; set { photo = value; OnPropertyChanged(); } }
        private string id_Household;
        public  string Id_Household { get => id_Household; set { id_Household = value; OnPropertyChanged(); } }
        private string placeOfBirth;
        public  string PlaceOfBirth { get => placeOfBirth; set { placeOfBirth = value; OnPropertyChanged(); } }
        private string address;
        public  string Address { get => address; set { address = value; OnPropertyChanged(); } }
        private Nullable<System.DateTime> dateOfBirth;
        public  Nullable<System.DateTime> DateOfBirth { get => dateOfBirth; set { dateOfBirth = value; OnPropertyChanged(); } }
        private Nullable<bool> sex;
        public  Nullable<bool> Sex { get => sex; set { sex = value; OnPropertyChanged(); } }
        private string relegion;
        public  string Relegion { get => relegion; set { relegion = value; OnPropertyChanged(); } }
        private string career;
        public  string Career { get => career; set { career = value; OnPropertyChanged(); } }
        private Nullable<bool> _isAbsence;
        public  Nullable<bool> isAbsence { get => _isAbsence; set { _isAbsence = value; OnPropertyChanged(); } }
        private Nullable<bool> _isTResidence;
        public  Nullable<bool> isTResidence { get => _isTResidence; set { _isTResidence = value; OnPropertyChanged(); } }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Family_Household> Family_Household { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Family_Household> Family_Household1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Household_Registration> Household_Registration { get; set; }
        public virtual Household_Registration Household_Registration1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Temporary_Absence> Temporary_Absence { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Temporary_Residence> Temporary_Residence { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transfer_Household> Transfer_Household { get; set; }
        
    }
}
